#
# Copyright (C) 2016 Jagan Teki <jagan@openedev.com>
#
# SPDX-License-Identifier:	GPL-2.0+

## spi-nor core
ifdef CONFIG_MTD_SPI_NOR
obj-y	+= spi-nor.o spi-nor-ids.o
endif

## spi-nor to spi interface driver
obj-$(CONFIG_MTD_M25P80)	+= m25p80.o
