#
# Copyright (C) 2016 Jagan Teki <jteki@openedev.com>
#
# SPDX-License-Identifier:	GPL-2.0+

ifdef CONFIG_MTD_SPI_NOR
obj-y += spi-nor.o
obj-y += spi-nor-ids.o
endif

obj-$(CONFIG_MTD_M25P80)	+= m25p80.o
